name: Update README

on:
  schedule:
    - cron: "0 0 * * 0" # Atualiza todo domingo
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update years of experience
        run: |
          START_YEAR=2005
          START_MONTH=5
          NOW_YEAR=$(date +%Y)
          NOW_MONTH=$(date +%m)
          YEARS=$((NOW_YEAR - START_YEAR))
          if [ "$NOW_MONTH" -lt "$START_MONTH" ]; then
            YEARS=$((YEARS - 1))
          fi
          sed -i "s/{{years_experience}}/${YEARS}/g" README.md
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update years of experience"
          git push
